zuul:
  routes:
     petclinic-restclient: /petclinic/**

server:
  port: 8765

ribbon:
    ConnectTimeout: 5000
    ReadTimeout: 5000
    MaxAutoRetries: 5
    MaxAutoRetriesNextServer: 5
    OkToRetryOnAllOperations: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/